### ISSUE TITLE
exception afer upgrading to v2

### ISSUE THREAD

**Issue by boneskull** [yeoman/generator#1038]
I have a custom generator [here](/boneskull/generator-bonestorm).

For whatever reason, v2.0.0 of this package is causing the failure below.  v1.1.1 does not exhibit this behavior.

It should be noted that the `src/` dir is *not* where my generators live!  They are transpiled by babel and put into `generators/`.  Removing `src` from my `files` property of `package.json` has no effect; I still get this error.

My generator is linked to my global Node install.  This is Node v8.5, yeoman v2.0.0, macOS.

```
/Users/boneskull/Documents/projects/generator-bonestorm/src/app/index.js:14
  constructor (args, opts) {
                           ^
TypeError: Class constructor Generator cannot be invoked without 'new'
    at new Bonestorm (/Users/boneskull/Documents/projects/generator-bonestorm/src/app/index.js:14:28)
    at Environment.instantiate (/usr/local/lib/node_modules/yo/node_modules/yeoman-environment/lib/environment.js:403:12)
    at Environment.create (/usr/local/lib/node_modules/yo/node_modules/yeoman-environment/lib/environment.js:381:17)
    at Environment.run (/usr/local/lib/node_modules/yo/node_modules/yeoman-environment/lib/environment.js:438:28)
    at env.lookup (/usr/local/lib/node_modules/yo/lib/cli.js:156:11)
    at Environment.resolver.lookup (/usr/local/lib/node_modules/yo/node_modules/yeoman-environment/lib/resolver.js:50:12)
    at init (/usr/local/lib/node_modules/yo/lib/cli.js:117:7)
    at pre (/usr/local/lib/node_modules/yo/lib/cli.js:76:3)
    at Object.<anonymous> (/usr/local/lib/node_modules/yo/lib/cli.js:205:3)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
    at Function.Module.runMain (module.js:609:10)
    at startup (bootstrap_node.js:158:16)
```

**Comment by SBoudrias** [comment]
Hey, I took a quick look and can't find anything obvious (especially that error is a bit weird).

I wonder if this could have something to do with the babel compilation result?

**Comment by boneskull** [comment]
Don’t think so... downgrading to pre-2.0.0 works fine. Can I provide more info?

**Comment by boneskull** [comment]
Oh rather that babel is choking on THIS package?  hmm....

**Comment by HsuTing** [comment]
I have same problem when I upgrade to v2.x and use `babel`.

**Comment by HsuTing** [comment]
I know why it will throw `TypeError`. Owing to `babel`, `babel` will transform `class` to `function` like:
```js
function App(args, options) {
  _classCallCheck(this, App);
  ...
}
```
This does not use `class` in `node.js`, but `Generator` is a `class` type in `node.js`. In the `class` which is transformed by `babel`, it will call a parent class as function. However, `class` in `node.js` is not a function. As a result, it will throw a TypeError.

I build a temporary package to support this problem: [@hsuting/yeoman-generator ](https://www.npmjs.com/package/@hsuting/yeoman-generator).
Hope this will help someone who faced the same problem as me.

**Comment by HsuTing** [comment]
I ask in `babel` slack and get the solution.
You can set the `.babelrc` as this:
```js
{
  presets: [
    ['env', {
      targets: {
        node: true
      }
    }]
  ]
}
```
This will not transform `class` to `function`.
And you can extends the `Generator` from `yeoman-generator@v2.x`.

**Comment by cjam** [comment]
Ran into this same issue while using typescript (no babel).  Downgrading to pre 2.x seems to have fixed it.

**Comment by christopher-taormina-zocdoc** [comment]
I've also run into the same issue, downgrading has helped me as well
